-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:40a7161d6b2361bda64ecf0c19523c65$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "glove1.png",
				spriteColorRect = { x = 40, y = 135, width = 366, height = 508 },
				textureRect = { x = 2, y = 2, width = 366, height = 508 },
				spriteSourceSize = { width = 480, height = 800 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "glove2.png",
				spriteColorRect = { x = 92, y = 190, width = 270, height = 384 },
				textureRect = { x = 2, y = 512, width = 270, height = 384 },
				spriteSourceSize = { width = 480, height = 800 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "glove3.png",
				spriteColorRect = { x = 136, y = 339, width = 198, height = 178 },
				textureRect = { x = 274, y = 512, width = 198, height = 178 },
				spriteSourceSize = { width = 480, height = 800 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

