-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:797d1e9a0ca66d8921a7b1dd50d8d2c3$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "loading 1.png",
				spriteColorRect = { x = 0, y = 0, width = 195, height = 47 },
				textureRect = { x = 2, y = 100, width = 195, height = 47 },
				spriteSourceSize = { width = 195, height = 47 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "loading 2.png",
				spriteColorRect = { x = 0, y = 0, width = 195, height = 47 },
				textureRect = { x = 2, y = 51, width = 195, height = 47 },
				spriteSourceSize = { width = 195, height = 47 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "loading 3.png",
				spriteColorRect = { x = 0, y = 0, width = 195, height = 47 },
				textureRect = { x = 2, y = 2, width = 195, height = 47 },
				spriteSourceSize = { width = 195, height = 47 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

