-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:e6bda9a6b3f6dc625f50003217c9c771$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "sound_off.png",
				spriteColorRect = { x = 6, y = 24, width = 108, height = 86 },
				textureRect = { x = 2, y = 106, width = 108, height = 86 },
				spriteSourceSize = { width = 108, height = 86 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sound_on.png",
				spriteColorRect = { x = 5, y = 17, width = 110, height = 102 },
				textureRect = { x = 2, y = 2, width = 110, height = 102 },
				spriteSourceSize = { width = 110, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

